name: stochastic-demand-opt
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - lightgbm
  - jupyter
  - ipykernel
  - pip:
    - -e .
